### ISSUE TITLE
Do not work properly with Cyrillic symbols

### ISSUE THREAD

**Issue by alexzhornyak** [mod-posh/Issue2ReleaseNotes#2]
If issue contains cyrillic symbols, they are replaced with question in output RELEASE.md file

**Example:**

**Issue Name:**
`[bug] [Texture Checker] Не включается чекер в сцене` 
| |
|---|
| ![image](https://github.com/mod-posh/Issue2ReleaseNotes/assets/18611095/7eefedca-6e9b-4c3a-b3cb-744a40345809) |

**Output Text:**
```
## NO LABEL

* issue-827: [bug] [Texture Checker] ?? ?????????? ????? ? ?????.
```

**Comment by jeffpatton1971** [comment]
Hey thanks for this feedback, let me see what I can get sorted for this.
